name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint HTML
        run: npx html-validate index.html || echo "HTML validation issues found, but continuing"
      
      - name: Lint CSS
        run: npx stylelint "**/*.css" || echo "CSS linting issues found, but continuing"
      
      - name: Lint JavaScript
        run: npx eslint "**/*.js" || echo "JavaScript linting issues found, but continuing"